# Generated by Django 6.0.4 on 2026-05-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
    ]
